version: 2.1
jobs:
  build:
    environment:
      IMAGE_NAME: test/building-on-ci
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t craft-frontend:latest ./docker-config/nginx
      - run:
          Name: Docker Login
          command: echo $GCLOUD_SERVICE_KEY | docker login -u _json_key --password-stdin https://eu.gcr.io
      - run: 
          Name: Docker tag
          command: docker tag craft-frontend gcr.io/917271558875/craft-frontend:tag1
      - run:
          Name: Push container
          command: docker push gcr.io/917271558875/craft-frontend:tag1
